# Forward Propogation

In [31]:
import numpy as np

In [32]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0,0,0,1]]).T
x.shape,y.shape

((4, 2), (4, 1))

In [33]:
def sig(z):
    return 1/(1+np.exp(-z))

In [34]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

#### for no hidden layer

In [74]:
# we want weights from -1 to 1 np.random gives from 0 to 1 so..
weights=2*np.random.random((2,1))-1                    # give 2 random no. 2*1 format....
bias=2*np.random.random(1)-1
weights,bias

(array([[ 0.08631259],
        [-0.8636579 ]]),
 array([0.0371208]))

In [84]:
lr=0.1
output0=x
output=sig(np.dot(output0,weights)+bias)
output

array([[0.0016093 ],
       [0.11486533],
       [0.09753416],
       [0.89691758]])

In [85]:
# for iter in range(1000):
#     first_term=output-y
#     input_for_last_layer=np.dot(output0,weights)+bias
#     second_term=derivativeSig(input_for_last_layer)
#     first_two=first_term*second_term
# #     first_two

#     changes=np.array([[0.0],[0.0]])
#     for i in range(2):
#         for j in range(4):
#             changes[i][0]+=first_two[j][0]*output0[j][i]
#     weights=weights-lr*changes
#     bias_change=0.0
#     for j in range(4):
#         bias_change+=first_two[j][0]*1
#     bias=bias-lr*bias_change

    
# output=sig(np.dot(x,weights)+bias)
# output,weights,bias

(array([[0.00088828],
        [0.07623275],
        [0.07662082],
        [0.88508531]]),
 array([[4.536163  ],
        [4.53066508]]),
 array([-7.02533405]))

In [86]:
# alternate to above step....
for iter in range(1000):
    first_term=output-y
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term=derivativeSig(input_for_last_layer)
    first_two=first_term*second_term
#     first_two

    changes=np.dot(output0.T,first_two)
    weights=weights-lr*changes
    bias_change=np.sum(first_two)
    bias=bias-lr*bias_change

    
output=sig(np.dot(x,weights)+bias)
output,weights,bias

(array([[6.93385984e-04],
        [8.30808088e-02],
        [8.31580799e-02],
        [9.22143453e-01]]),
 array([[4.87303842],
        [4.8720245 ]]),
 array([-7.27323011]))

#### for one layer

In [87]:
# model
#          S00     S10
#                             Result
#          S01     S11

In [115]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0,1,1,0]]).T
x.shape,y.shape

((4, 2), (4, 1))

In [116]:
def sig(z):
    return 1/(1+np.exp(-z))

In [117]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [118]:
# one hidden layer weights
wh=2*np.random.random((2,2))-1
bh=2*np.random.random((1,2))-1
w0=2*np.random.random((2,1))-1
b0=2*np.random.random((1,1))-1

In [119]:
lr=0.1

In [120]:
# forward propogation with one hidden layer..
for itr in range(10000):
    output0=x
    input_hidden=np.dot(output0,wh)+bh
    output_hidden=sig(input_hidden)
    inputForOutputLayer=np.dot(output_hidden,w0)+b0
    output=sig(inputForOutputLayer)


    first_term_output_layer=output-y
    second_term_output_layer=derivativeSig(inputForOutputLayer)
    first_two_output_layer=first_term_output_layer*second_term_output_layer

    first_term_hidden_layer=np.dot(first_two_output_layer,w0.T)
    second_term_hidden_layer=derivativeSig(input_hidden)
    first_two_hidden_layer=first_term_hidden_layer*second_term_hidden_layer

    changes_output=np.dot(output_hidden.T,first_two_output_layer)
    changes_output_bias=np.sum(first_two_output_layer,keepdims=True,axis=0)         # keep dimension

    changes_hidden=np.dot(output0.T,first_two_hidden_layer)
    changes_hidden_bias=np.sum(first_two_hidden_layer,keepdims=True,axis=0)         # keep dimension

    w0=w0-lr*changes_output
    b0=b0-lr*changes_output_bias

    wh=wh-lr*changes_hidden
    bh=bh-lr*changes_hidden_bias


output0=x
input_hidden=np.dot(output0,wh)+bh
output_hidden=sig(input_hidden)
inputForOutputLayer=np.dot(output_hidden,w0)+b0
output=sig(inputForOutputLayer)
output,wh,bh,w0,b0

(array([[0.06447044],
        [0.93944466],
        [0.939844  ],
        [0.06599862]]),
 array([[3.5480224 , 5.91296715],
        [3.52699724, 5.79201333]]),
 array([[-5.40573284, -2.40811115]]),
 array([[-7.94060314],
        [ 7.27248218]]),
 array([[-3.23979504]]))

In [121]:
output

array([[0.06447044],
       [0.93944466],
       [0.939844  ],
       [0.06599862]])

In [122]:
# our output is close to 0 1 1 0 

In [123]:
wh,bh,w0,b0

(array([[3.5480224 , 5.91296715],
        [3.52699724, 5.79201333]]),
 array([[-5.40573284, -2.40811115]]),
 array([[-7.94060314],
        [ 7.27248218]]),
 array([[-3.23979504]]))

In [124]:
# we can also see that it has implemented and , Nor and used output of them as Nor(and,Nor) to give XOR